// boost.units_blas
//
// Copyright (C) 2008 T. Zachary Laine
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_UNITS_BLAS_CONFIG_HPP
#define BOOST_UNITS_BLAS_CONFIG_HPP


#ifndef BOOST_UNITS_BLAS_USE_OPERATORS_FOR_MATRIX_OPERATIONS
# define BOOST_UNITS_BLAS_USE_OPERATORS_FOR_MATRIX_OPERATIONS 1
#endif

#ifndef BOOST_UNITS_BLAS_USE_INEXACT_DETERMINANT_TYPE
# define BOOST_UNITS_BLAS_USE_INEXACT_DETERMINANT_TYPE 0
#endif

#ifndef BOOST_UNITS_BLAS_ENFORCE_FUSION_VECTOR_MATRIX_TEMPLATE_PARAMETERS
# define BOOST_UNITS_BLAS_ENFORCE_FUSION_VECTOR_MATRIX_TEMPLATE_PARAMETERS 0
#endif

#endif // BOOST_UNITS_BLAS_CONFIG_HPP
